### ISSUE TITLE
县识别成市了

### ISSUE THREAD

**Issue by zhl11b** [sleagon/chinaid#1]
县识别成市，测试例子是县级市

**Comment by sleagon** [comment]
![image](https://user-images.githubusercontent.com/7693290/42691790-fd599c74-86db-11e8-8b55-3346aa43693b.png)

多谢提醒，枣阳确实是县级市，不过在民政部网站上行政区划分的确实是“枣阳市”而不是“枣阳县”，现在也很少说湖北省-襄阳市-枣阳县了，一般都是湖北省-枣阳市。

**Comment by zhl11b** [comment]
不是 我的意思是说如果有县级行政区域，也会被识别到city里面，city含义是市，感觉不太好。

**Comment by sleagon** [comment]
哦哦哦，理解错你的意思了，已经改过来了，万分感谢~~~~~~~
现在按三级行政区输出了，原来的citycode也换成code了，避免理解错误。
```json
{
    "sex":1,
    "birthday":"1990-06-04T00:00:00Z",
    "code":420683,
    "province":"湖北省",
    "city":"襄阳市",
    "district":"枣阳市"
}
```
