### ISSUE TITLE
地址码的网址能发一下吗，我怎么觉得你转换出来的好多数据是错的

### ISSUE THREAD

**Issue by chennqqi** [sleagon/chinaid#2]

**Comment by sleagon** [comment]
这个是民政部官网的，去网站里的行政区划分就可以找到，应该不会错的呀。比如最新的今年4月份的在这里：http://www.mca.gov.cn/article/sj/xzqh/2019/201901-06/201905271021.html


如果有错误的欢迎指出来哈~

**Comment by sleagon** [comment]
@chennqqi 刚看了一下，确实有可能识别错误，主要的问题是身份证是按照老的行政区数据签发的，行政区划分变动会删除老的行政区，这样的话遇到老的行政区的身份证就会出错。你可以更新一下这个包，应该就没问题了。如果还有问题，可以给个有问题的例子，我再看看。
